version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installation
          command: |
              sudo apt-get update
              sudo apt-get install -y cmake python-pytest
      - run:
          name: Build
          command: |
              mkdir bld
              cd bld
              cmake ..
              make
      - run:
          name: Test
          command: |
              cd bld
              ctest --no-compress-stdout -T Test
              mkdir -p Testing/test-reports/c
              mkdir -p Testing/test-reports/python
              mv Testing/*/*.xml Testing/test-reports/c
              mv Testing/*.xml Testing/test-reports/python
      - store_test_results:
          path: bld/Testing/test-reports
